spring:
  datasource:
    username: root
    password: 1913
    #    假如时间报错了，就增加一个时区的配置 serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/tiktok?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#整合mybatis
mybatis:
  type-aliases-package: com.example.springboot_05_mybatis.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml


